"""Curated seed for the knowledge graph.

This is the hand-authored, high-precision starting wiring: macro factors with
their stable points, policy actors, themes/sectors, and a multi-market asset
universe (US / HK / China A / Singapore / crypto — all reachable via Longbridge
or yfinance). LLM-proposed edges get appended on top over time with provenance;
they never replace these.

Sign convention: node "value" going UP means the named quantity rises (a rate
node up = tightening; a tension node up = more tension). Edge sign +1 means the
destination moves the same way as the source. `delay_days` on an edge is the
world-systems τ: the effect lands that many days later via the field's pending
queue, not in the same cycle.

Bump SEED_VERSION whenever curated nodes/edges change — existing
knowledge_graph.json files merge the update in on next load (LLM-proposed edges
are preserved).
"""

SEED_VERSION = 11

SEED_NODES = [
    # ------------- macro factors (with stable points) -------------
    {"id": "fed_rate", "type": "factor", "label": "Fed policy rate",
     "aliases": ["federal reserve", "fed", "fomc", "us interest rate", "rate hike", "rate cut"],
     "equilibrium": "neutral ~3%; far above = restrictive, cuts loom; far below = stimulative"},
    {"id": "us_inflation", "type": "factor", "label": "US inflation",
     "aliases": ["cpi", "inflation", "pce"],
     "equilibrium": "Fed target 2% yoy; >3% forces hawkishness, <2% permits easing"},
    {"id": "us_10y_yield", "type": "factor", "label": "US 10Y yield",
     "aliases": ["treasury yield", "10-year", "long rates", "bond yields"],
     "equilibrium": "3.5-4.5% consistent with 2% inflation + real growth"},
    {"id": "usd_strength", "type": "factor", "label": "US dollar",
     "aliases": ["dollar index", "dxy", "greenback", "dollar"],
     "equilibrium": "DXY ~95-105; strong USD tightens global liquidity"},
    {"id": "risk_appetite", "type": "factor", "label": "Global risk appetite",
     "aliases": ["risk-on", "risk-off", "vix", "volatility", "market fear"],
     "equilibrium": "VIX 12-20 = calm; >25 = fear; <12 = complacency (fragile)"},
    {"id": "global_growth", "type": "factor", "label": "Global growth",
     "aliases": ["gdp growth", "recession", "pmi", "manufacturing activity", "soft landing"],
     "equilibrium": "global PMI ~50; below = contraction"},
    {"id": "oil_price", "type": "commodity", "label": "Crude oil",
     "aliases": ["brent", "wti", "crude", "opec cut", "oil supply"],
     "equilibrium": "$65-85 balances producers and consumers; >$95 is an inflation shock"},
    {"id": "gold_price", "type": "commodity", "label": "Gold",
     "aliases": ["bullion", "safe haven", "xau"],
     "equilibrium": "rises on real-rate falls, USD weakness, fear"},
    {"id": "copper_price", "type": "commodity", "label": "Copper",
     "aliases": ["industrial metals", "dr copper"],
     "equilibrium": "tracks China/global industrial demand; the growth bellwether"},
    {"id": "lithium_price", "type": "commodity", "label": "Lithium",
     "aliases": ["battery metals", "lithium carbonate"],
     "equilibrium": "boom-bust vs EV demand; low prices squeeze miners, help battery makers"},
    {"id": "ai_capex_cycle", "type": "factor", "label": "AI capex cycle",
     "aliases": ["ai spending", "datacenter buildout", "gpu demand", "ai bubble"],
     "equilibrium": "hyperscaler capex growth >0; a guidance cut from any mega-cap cracks it"},
    {"id": "crypto_liquidity", "type": "factor", "label": "Crypto liquidity",
     "aliases": ["etf inflows", "stablecoin supply", "crypto flows", "bitcoin etf"],
     "equilibrium": "follows global liquidity + risk appetite; halving cycles overlay"},
    {"id": "geopolitical_tension", "type": "factor", "label": "Geopolitical tension",
     "aliases": ["war", "conflict", "taiwan strait", "middle east", "strait of hormuz"],
     "equilibrium": "baseline simmer; escalation lifts oil/gold, sinks risk appetite"},
    {"id": "us_china_tariffs", "type": "factor", "label": "US-China trade policy",
     "aliases": ["tariff", "trade war", "trade deal", "export tariffs", "decoupling"],
     "equilibrium": "managed friction; escalation hits supply chains + China exporters"},
    {"id": "china_export_controls", "type": "factor", "label": "Chip export controls",
     "aliases": ["chip ban", "semiconductor restrictions", "entity list", "chip curbs"],
     "equilibrium": "tightening trend; each round reprices AI/semi China revenue"},
    # ------------- world-systems additions (liquidity, credit, real economy) -------------
    {"id": "money_supply", "type": "factor", "label": "Global liquidity / money supply",
     "aliases": ["m2", "qe", "quantitative easing", "quantitative tightening", "liquidity injection", "balance sheet runoff"],
     "equilibrium": "expanding with nominal GDP; QT drains risk assets, QE floats them"},
    {"id": "us_gov_debt", "type": "factor", "label": "US government debt / fiscal",
     "aliases": ["deficit", "debt ceiling", "treasury auction", "treasury issuance", "credit rating downgrade", "fiscal deficit"],
     "equilibrium": "sustainable while demand absorbs issuance; failed auctions/downgrades reprice the long end"},
    {"id": "bond_stress", "type": "factor", "label": "US Treasury market stress",
     "aliases": ["bond selloff", "failed auction", "bond vigilantes", "move index",
                 "treasury liquidity", "term premium"],
     "equilibrium": "orderly auctions, MOVE subdued; stress = fiscal doubt priced into the long end"},
    {"id": "japan_debt", "type": "factor", "label": "Japan debt / JGB market",
     "aliases": ["jgb", "japan bond yields", "yield curve control", "japan fiscal"],
     "equilibrium": "~250%% GDP sustainable ONLY at near-zero yields; JGB stress forces repatriation from US Treasuries"},
    {"id": "china_growth", "type": "factor", "label": "China growth",
     "aliases": ["china gdp", "china pmi", "china exports", "china industrial output"],
     "equilibrium": "~5%% target; property drag vs stimulus push decides which side of it"},
    {"id": "korea_growth", "type": "factor", "label": "Korea economy / exports",
     "aliases": ["korea exports", "kospi", "korea chips", "value-up program", "korean won"],
     "equilibrium": "export-levered (chips ~20%% of exports): amplifies both the AI cycle and China demand"},
    {"id": "credit_conditions", "type": "factor", "label": "Credit availability / banking system",
     "aliases": ["credit crunch", "bank lending", "loan defaults", "credit spreads", "bank failure", "npl"],
     "equilibrium": "spreads tight, lending flowing; a crunch (node DOWN) chokes growth with a lag"},
    {"id": "us_employment", "type": "factor", "label": "US labor market",
     "aliases": ["payrolls", "nonfarm", "jobless claims", "layoffs", "unemployment rate", "job cuts"],
     "equilibrium": "unemployment ~4%; hot labor keeps the Fed hawkish, cracks precede recessions"},
    {"id": "us_consumer", "type": "factor", "label": "US consumer spending/confidence",
     "aliases": ["retail sales", "consumer confidence", "consumer spending", "holiday sales"],
     "equilibrium": "~70% of US GDP; rolls over when savings deplete and hiring stalls"},
    {"id": "us_elections", "type": "factor", "label": "US election cycle",
     "aliases": ["midterms", "election", "presidential race", "campaign"],
     "equilibrium": "quadrennial vol; policy promises move tariffs, regulation, deficits"},
    {"id": "sanctions", "type": "factor", "label": "Sanctions regime",
     "aliases": ["sanction", "embargo", "asset freeze", "secondary sanctions"],
     "equilibrium": "ratcheting tool of statecraft; new rounds hit energy flows and targeted sectors"},
    {"id": "shipping_costs", "type": "factor", "label": "Shipping / supply chains",
     "aliases": ["freight rates", "red sea", "suez", "panama canal", "container rates", "port congestion", "supply chain"],
     "equilibrium": "boring when normal; chokepoint disruptions feed inflation with ~1-2 month lag"},
    {"id": "rare_earths", "type": "factor", "label": "Critical minerals / rare earths",
     "aliases": ["rare earth", "gallium", "germanium", "graphite export", "critical minerals"],
     "equilibrium": "China's counter-lever in the trade war; export curbs squeeze chips/EV/defense"},
    {"id": "power_demand", "type": "factor", "label": "Electricity / datacenter power",
     "aliases": ["electricity demand", "power grid", "datacenter power", "uranium", "nuclear power", "power shortage"],
     "equilibrium": "AI buildout is power-constrained; shortages throttle datacenter growth"},
    {"id": "defense_spending", "type": "factor", "label": "Defense spending",
     "aliases": ["defense budget", "military spending", "rearmament", "nato spending"],
     "equilibrium": "ratchets up with tension (slowly, budget cycles), rarely back down"},
    {"id": "nickel_price", "type": "commodity", "label": "Nickel",
     "aliases": ["nickel", "indonesia nickel"],
     "equilibrium": "battery + stainless demand vs Indonesian supply flood"},
    {"id": "silver_price", "type": "commodity", "label": "Silver",
     "aliases": ["silver", "xag"],
     "equilibrium": "half monetary metal (tracks gold), half industrial (solar paste)"},
    {"id": "uranium_price", "type": "commodity", "label": "Uranium",
     "aliases": ["u3o8", "yellowcake", "nuclear fuel"],
     "equilibrium": "structural deficit vs nuclear restart wave; datacenter power tightens it"},
    {"id": "energy_transition", "type": "factor", "label": "Energy transition policy",
     "aliases": ["renewables", "climate policy", "green energy", "solar subsidies", "net zero", "ira credits"],
     "equilibrium": "subsidy-driven; policy reversals whipsaw solar/wind harder than demand does"},
    {"id": "natural_gas", "type": "commodity", "label": "Natural gas",
     "aliases": ["lng", "natgas", "gas prices", "henry hub", "ttf"],
     "equilibrium": "regional markets linked by LNG; cold winters + outages spike it"},
    # ------------- China factor cluster -------------
    {"id": "pboc_rate", "type": "factor", "label": "PBOC policy rate",
     "aliases": ["pboc", "lpr", "china rate cut", "rrr cut", "people's bank of china"],
     "equilibrium": "easing bias while property deleverages; cuts squeeze bank NIMs"},
    {"id": "china_stimulus", "type": "factor", "label": "China fiscal stimulus",
     "aliases": ["china stimulus", "special bonds", "consumption vouchers", "politburo stimulus"],
     "equilibrium": "episodic; big packages lift consumer + property + commodities"},
    {"id": "china_property", "type": "factor", "label": "China property sector",
     "aliases": ["evergrande", "country garden", "china real estate", "home sales china"],
     "equilibrium": "still deleveraging; stabilization = major risk-on for China assets"},
    {"id": "china_consumer", "type": "factor", "label": "China consumer demand",
     "aliases": ["china retail sales", "china consumption", "singles day", "china spending"],
     "equilibrium": "soft since 2021; hostage to property wealth effect + confidence"},
    {"id": "china_anti_corruption", "type": "factor", "label": "China anti-corruption drive",
     "aliases": ["anti-corruption", "austerity campaign", "graft crackdown", "common prosperity"],
     "equilibrium": "recurring campaigns suppress luxury/baijiu gifting demand"},
    {"id": "yen_carry", "type": "factor", "label": "BOJ policy / yen carry",
     "aliases": ["boj", "bank of japan", "yen", "carry trade", "japan rate hike"],
     "equilibrium": "BOJ normalization unwinds carry trades -> global risk-off spasms"},
    {"id": "mas_policy", "type": "factor", "label": "MAS policy (SGD)",
     "aliases": ["mas", "monetary authority of singapore", "sgd neer", "singapore policy"],
     "equilibrium": "SGD appreciation path; SG rates import US rates -> bank NIMs, REIT costs"},
    # ------------- global coverage (seed v3) -------------
    {"id": "ecb_policy", "type": "factor", "label": "ECB policy",
     "aliases": ["ecb", "european central bank", "lagarde", "eurozone rates"],
     "equilibrium": "tracks eurozone inflation to 2%; divergence vs Fed moves EUR/USD"},
    {"id": "europe_growth", "type": "factor", "label": "Europe growth",
     "aliases": ["eurozone economy", "germany economy", "eu growth", "european recession"],
     "equilibrium": "structurally slow; energy shocks and China demand swing it"},
    {"id": "india_growth", "type": "factor", "label": "India growth",
     "aliases": ["india economy", "india gdp", "rbi", "modi economy"],
     "equilibrium": "fastest large economy; oil-import sensitive"},
    {"id": "em_flows", "type": "factor", "label": "EM capital flows",
     "aliases": ["emerging market flows", "em outflows", "foreign investors"],
     "equilibrium": "follow USD inversely; sudden stops hit all EM at once"},
    {"id": "us_tech_regulation", "type": "factor", "label": "US tech regulation",
     "aliases": ["antitrust", "ai regulation", "big tech probe", "ftc lawsuit"],
     "equilibrium": "simmering; a breakup ruling or AI act reprices mega-caps"},
    {"id": "crypto_regulation", "type": "factor", "label": "Crypto regulation (up = tightening)",
     "aliases": ["crypto crackdown", "stablecoin law", "etf approval", "sec crypto"],
     "equilibrium": "approvals (node DOWN) unlock flows; crackdowns choke liquidity"},
    {"id": "ai_circularity", "type": "factor", "label": "AI circular financing (up = more round-tripping)",
     "aliases": ["circular deals", "vendor financing", "round-tripping", "circular revenue",
                 "gpu-backed loans", "invest in customer"],
     "equilibrium": "some vendor financing is normal capex grease; when the circle IS the growth story, the revenue is partly fictitious and the unwind is violent"},
    {"id": "crypto_adoption", "type": "factor", "label": "Crypto institutional adoption",
     "aliases": ["corporate treasury bitcoin", "institutional crypto", "tokenization",
                 "crypto etf inflows", "sovereign bitcoin reserve"],
     "equilibrium": "one-way ratchet so far: each adoption wave (ETFs, treasuries, states) resets the floor"},
    {"id": "btc_halving", "type": "factor", "label": "BTC halving / supply cycle",
     "aliases": ["halving", "bitcoin supply", "miner capitulation"],
     "equilibrium": "4-year supply schedule; the cycle narrative moves flows even when fundamentals don't"},
    {"id": "oil_supply", "type": "factor", "label": "Oil supply (up = more barrels)",
     "aliases": ["production increase", "shale output", "spare capacity", "oil glut"],
     "equilibrium": "OPEC discipline vs shale; gluts cap prices, outages spike them"},
    {"id": "agri_food", "type": "commodity", "label": "Food / agriculture prices",
     "aliases": ["wheat", "grain prices", "food prices", "harvest", "el nino"],
     "equilibrium": "weather + fertilizer + export bans; feeds EM inflation hardest"},
    # ------------- policy actors -------------
    {"id": "us_government", "type": "actor", "label": "US government",
     "aliases": ["white house", "congress", "us president", "treasury", "sec"]},
    {"id": "china_government", "type": "actor", "label": "China government",
     "aliases": ["beijing", "politburo", "state council", "xi jinping", "csrc"]},
    {"id": "opec", "type": "actor", "label": "OPEC+",
     "aliases": ["opec", "saudi arabia oil", "production quota"]},
    {"id": "temasek", "type": "actor", "label": "Temasek",
     "aliases": ["temasek holdings", "gic"]},
    # ------------- themes / sectors -------------
    {"id": "us_megacap_tech", "type": "theme", "label": "US mega-cap tech",
     "aliases": ["magnificent seven", "big tech", "nasdaq"]},
    {"id": "semis", "type": "theme", "label": "Semiconductors",
     "aliases": ["chips", "semiconductor", "foundry", "chipmakers"]},
    {"id": "ai_datacenter", "type": "theme", "label": "AI / datacenter",
     "aliases": ["artificial intelligence", "datacenter", "gpu", "accelerators"]},
    {"id": "ev_supply_chain", "type": "theme", "label": "EV supply chain",
     "aliases": ["electric vehicle", "ev battery", "ev makers"]},
    {"id": "china_tech", "type": "theme", "label": "China internet/tech",
     "aliases": ["china tech", "kweb", "china internet", "hang seng tech"]},
    {"id": "china_financials", "type": "theme", "label": "China banks/financials",
     "aliases": ["china banks", "chinese lenders", "bank nim china"]},
    {"id": "china_staples", "type": "theme", "label": "China consumer staples/luxury",
     "aliases": ["baijiu", "china liquor", "china staples"]},
    {"id": "energy_sector", "type": "sector", "label": "Energy sector",
     "aliases": ["oil majors", "energy stocks"]},
    {"id": "consumer_staples", "type": "sector", "label": "Consumer staples (defensive)",
     "aliases": ["defensives", "staples"]},
    {"id": "sg_banks", "type": "theme", "label": "Singapore banks",
     "aliases": ["singapore banks", "sg lenders"]},
    {"id": "sg_reits", "type": "theme", "label": "Singapore REITs",
     "aliases": ["s-reits", "singapore reits"]},
    {"id": "crypto_majors", "type": "theme", "label": "Crypto majors",
     "aliases": ["cryptocurrency", "bitcoin", "digital assets"]},
    {"id": "europe_equities", "type": "theme", "label": "Europe equities",
     "aliases": ["dax", "stoxx", "european stocks"]},
    {"id": "korea_equities", "type": "theme", "label": "Korea equities",
     "aliases": ["kospi stocks", "korean stocks"]},
    {"id": "japan_equities", "type": "theme", "label": "Japan equities",
     "aliases": ["nikkei", "topix", "japanese stocks"]},
    {"id": "india_equities", "type": "theme", "label": "India equities",
     "aliases": ["nifty", "sensex", "indian stocks"]},
    {"id": "global_luxury", "type": "theme", "label": "Global luxury",
     "aliases": ["luxury goods", "louis vuitton", "gucci", "hermes", "high-end retail"]},
    {"id": "sportswear", "type": "theme", "label": "Sportswear / consumer brands",
     "aliases": ["athleisure", "sneakers", "apparel brands"]},
    {"id": "healthcare", "type": "theme", "label": "Healthcare / pharma",
     "aliases": ["pharma", "drugmakers", "medical", "drug pricing"]},
    {"id": "food_beverage", "type": "theme", "label": "Food & beverage",
     "aliases": ["packaged food", "beverages", "soft drinks", "restaurants", "fast food"]},
    {"id": "china_fnb", "type": "theme", "label": "China F&B / new consumer",
     "aliases": ["bubble tea", "milk tea", "china restaurants", "china ipo", "new tea drinks"]},
    {"id": "solar", "type": "theme", "label": "Solar / renewables",
     "aliases": ["photovoltaic", "solar panels", "clean energy stocks"]},
    {"id": "miners", "type": "theme", "label": "Miners / raw materials",
     "aliases": ["mining stocks", "resource companies"]},
    {"id": "robotics", "type": "theme", "label": "Robotics / automation",
     "aliases": ["industrial robots", "humanoid robots", "factory automation", "cobots"]},
    {"id": "cybersecurity", "type": "theme", "label": "Cybersecurity",
     "aliases": ["cyber attack", "ransomware", "hack", "data breach", "zero-day"]},
    {"id": "hardware_chain", "type": "theme", "label": "Hardware supply chain",
     "aliases": ["components", "contract manufacturing", "foundry", "hbm", "memory chips"]},
    {"id": "us_financials", "type": "theme", "label": "US banks/financials",
     "aliases": ["us banks", "wall street banks", "regional banks"]},
    {"id": "defense_industry", "type": "theme", "label": "Defense industry",
     "aliases": ["defense stocks", "arms makers", "defense contractors"]},
    # ------------- assets: US -------------
    {"id": "aapl", "type": "asset", "label": "Apple", "symbol": "AAPL", "market": "US",
     "aliases": ["iphone"]},
    {"id": "msft", "type": "asset", "label": "Microsoft", "symbol": "MSFT", "market": "US",
     "aliases": ["azure"]},
    {"id": "nvda", "type": "asset", "label": "Nvidia", "symbol": "NVDA", "market": "US",
     "aliases": ["h100", "blackwell"]},
    {"id": "tsla", "type": "asset", "label": "Tesla", "symbol": "TSLA", "market": "US",
     "aliases": ["elon musk"]},
    {"id": "xlk", "type": "asset", "label": "Tech sector ETF", "symbol": "XLK", "market": "US"},
    {"id": "xle", "type": "asset", "label": "Energy sector ETF", "symbol": "XLE", "market": "US"},
    {"id": "xlp", "type": "asset", "label": "Staples sector ETF", "symbol": "XLP", "market": "US"},
    {"id": "gld", "type": "asset", "label": "Gold ETF", "symbol": "GLD", "market": "US"},
    {"id": "uso", "type": "asset", "label": "Oil ETF", "symbol": "USO", "market": "US"},
    {"id": "xlf", "type": "asset", "label": "Financials ETF", "symbol": "XLF", "market": "US"},
    {"id": "ita", "type": "asset", "label": "Defense ETF", "symbol": "ITA", "market": "US"},
    {"id": "tlt", "type": "asset", "label": "20Y+ Treasury ETF", "symbol": "TLT", "market": "US",
     "aliases": ["long bonds"]},
    {"id": "vgk", "type": "asset", "label": "Europe ETF", "symbol": "VGK", "market": "US"},
    {"id": "ewj", "type": "asset", "label": "Japan ETF", "symbol": "EWJ", "market": "US"},
    {"id": "inda", "type": "asset", "label": "India ETF", "symbol": "INDA", "market": "US"},
    {"id": "dba", "type": "asset", "label": "Agriculture ETF", "symbol": "DBA", "market": "US"},
    # consumer brands & consumables
    {"id": "lvmh", "type": "asset", "label": "LVMH", "symbol": "MC.PA", "market": "EU",
     "aliases": ["lvmuy", "louis vuitton", "dior", "moet"]},
    {"id": "prada", "type": "asset", "label": "Prada", "symbol": "1913.HK", "market": "HK"},
    {"id": "nike", "type": "asset", "label": "Nike", "symbol": "NKE", "market": "US"},
    {"id": "adidas", "type": "asset", "label": "adidas", "symbol": "ADS.DE", "market": "EU"},
    {"id": "anta", "type": "asset", "label": "Anta Sports", "symbol": "2020.HK", "market": "HK"},
    {"id": "lining", "type": "asset", "label": "Li-Ning", "symbol": "2331.HK", "market": "HK",
     "aliases": ["li ning"]},
    {"id": "xlv", "type": "asset", "label": "Healthcare ETF", "symbol": "XLV", "market": "US"},
    {"id": "jnj", "type": "asset", "label": "Johnson & Johnson", "symbol": "JNJ", "market": "US",
     "aliases": ["johnson and johnson"]},
    {"id": "ko", "type": "asset", "label": "Coca-Cola", "symbol": "KO", "market": "US",
     "aliases": ["coke", "coca cola"]},
    {"id": "nongfu", "type": "asset", "label": "Nongfu Spring", "symbol": "9633.HK", "market": "HK",
     "aliases": ["nongfu spring"]},
    {"id": "mcd", "type": "asset", "label": "McDonald's", "symbol": "MCD", "market": "US",
     "aliases": ["mcdonalds", "mcdonald's"]},
    {"id": "sbux", "type": "asset", "label": "Starbucks", "symbol": "SBUX", "market": "US"},
    {"id": "yumchina", "type": "asset", "label": "Yum China (KFC/Pizza Hut)", "symbol": "9987.HK",
     "market": "HK", "aliases": ["yum china", "kfc china"]},
    {"id": "mixue", "type": "asset", "label": "Mixue (bubble tea)", "symbol": "2097.HK",
     "market": "HK", "aliases": ["mixue bingcheng"]},
    {"id": "haidilao", "type": "asset", "label": "Haidilao hotpot", "symbol": "6862.HK", "market": "HK"},
    {"id": "popmart", "type": "asset", "label": "Pop Mart", "symbol": "9992.HK", "market": "HK",
     "aliases": ["pop mart", "labubu"]},
    {"id": "luckin", "type": "asset", "label": "Luckin Coffee", "symbol": "LKNCY", "market": "US",
     "aliases": ["luckin"]},
    {"id": "crbeer", "type": "asset", "label": "CR Beer", "symbol": "0291.HK", "market": "HK",
     "aliases": ["china resources beer", "snow beer"]},
    {"id": "mengniu", "type": "asset", "label": "Mengniu Dairy", "symbol": "2319.HK", "market": "HK"},
    {"id": "unipres", "type": "asset", "label": "Uni-President China", "symbol": "0220.HK",
     "market": "HK", "aliases": ["uni-president"]},
    # ---- ownership chain nodes (follow the money) ----
    {"id": "pdd", "type": "asset", "label": "PDD (Pinduoduo/Temu)", "symbol": "PDD", "market": "US",
     "aliases": ["pinduoduo", "temu"]},
    {"id": "sea", "type": "asset", "label": "Sea (Shopee/Garena)", "symbol": "SE", "market": "US",
     "aliases": ["shopee", "garena"]},
    {"id": "prosus", "type": "asset", "label": "Prosus", "symbol": "PRX.AS", "market": "EU",
     "aliases": ["naspers"]},
    {"id": "softbank", "type": "asset", "label": "SoftBank", "symbol": "9984.T", "market": "JP",
     "aliases": ["masayoshi son", "vision fund"]},
    {"id": "arm", "type": "asset", "label": "Arm Holdings", "symbol": "ARM", "market": "US"},
    {"id": "berkshire", "type": "asset", "label": "Berkshire Hathaway", "symbol": "BRK-B",
     "market": "US", "aliases": ["warren buffett", "berkshire"]},
    {"id": "crwv", "type": "asset", "label": "CoreWeave", "symbol": "CRWV", "market": "US",
     "aliases": ["coreweave"]},
    {"id": "coin", "type": "asset", "label": "Coinbase", "symbol": "COIN", "market": "US"},
    {"id": "mstr", "type": "asset", "label": "Strategy (MicroStrategy)", "symbol": "MSTR",
     "market": "US", "aliases": ["microstrategy", "saylor"]},
    # ---- hardware / supply-chain nodes ----
    {"id": "tsmc", "type": "asset", "label": "TSMC", "symbol": "TSM", "market": "US",
     "aliases": ["taiwan semiconductor", "2330.TW"]},
    {"id": "asml", "type": "asset", "label": "ASML", "symbol": "ASML", "market": "US",
     "aliases": ["euv lithography"]},
    {"id": "amd", "type": "asset", "label": "AMD", "symbol": "AMD", "market": "US"},
    {"id": "micron", "type": "asset", "label": "Micron", "symbol": "MU", "market": "US",
     "aliases": ["hbm memory"]},
    {"id": "skhynix", "type": "asset", "label": "SK Hynix", "symbol": "000660.KS", "market": "KR",
     "aliases": ["sk hynix", "hynix"]},
    {"id": "samsung", "type": "asset", "label": "Samsung Electronics", "symbol": "005930.KS",
     "market": "KR", "aliases": ["samsung"]},
    {"id": "ewy", "type": "asset", "label": "Korea ETF", "symbol": "EWY", "market": "US"},
    {"id": "foxconn", "type": "asset", "label": "Foxconn (Hon Hai)", "symbol": "2317.TW",
     "market": "TW", "aliases": ["hon hai"]},
    {"id": "sunny", "type": "asset", "label": "Sunny Optical", "symbol": "2382.HK", "market": "HK",
     "aliases": ["sunny optical"]},
    {"id": "ganfeng", "type": "asset", "label": "Ganfeng Lithium", "symbol": "1772.HK",
     "market": "HK", "aliases": ["ganfeng"]},
    # ---- raw materials / miners / energy transition ----
    {"id": "alb", "type": "asset", "label": "Albemarle (lithium)", "symbol": "ALB", "market": "US"},
    {"id": "gdx", "type": "asset", "label": "Gold Miners ETF", "symbol": "GDX", "market": "US",
     "aliases": ["gold miners"]},
    {"id": "zijin", "type": "asset", "label": "Zijin Mining (gold/copper)", "symbol": "2899.HK",
     "market": "HK", "aliases": ["zijin"]},
    {"id": "vale", "type": "asset", "label": "Vale (iron ore/nickel)", "symbol": "VALE",
     "market": "US"},
    {"id": "cameco", "type": "asset", "label": "Cameco (uranium)", "symbol": "CCJ", "market": "US"},
    {"id": "fslr", "type": "asset", "label": "First Solar (US)", "symbol": "FSLR", "market": "US"},
    {"id": "jks", "type": "asset", "label": "JinkoSolar (China)", "symbol": "JKS", "market": "US",
     "aliases": ["jinko"]},
    {"id": "longi", "type": "asset", "label": "LONGi Green (China)", "symbol": "601012.SS",
     "market": "CN", "aliases": ["longi"]},
    {"id": "tan", "type": "asset", "label": "Solar ETF", "symbol": "TAN", "market": "US"},
    {"id": "intc", "type": "asset", "label": "Intel", "symbol": "INTC", "market": "US"},
    {"id": "mp", "type": "asset", "label": "MP Materials (rare earths)", "symbol": "MP",
     "market": "US", "aliases": ["mountain pass"]},
    # ---- robotics ----
    {"id": "fanuc", "type": "asset", "label": "Fanuc", "symbol": "6954.T", "market": "JP"},
    {"id": "ubtech", "type": "asset", "label": "UBTech Robotics", "symbol": "9880.HK",
     "market": "HK", "aliases": ["ubtech"]},
    {"id": "botz", "type": "asset", "label": "Robotics ETF", "symbol": "BOTZ", "market": "US"},
    # ---- cybersecurity ----
    {"id": "crwd", "type": "asset", "label": "CrowdStrike", "symbol": "CRWD", "market": "US"},
    {"id": "panw", "type": "asset", "label": "Palo Alto Networks", "symbol": "PANW", "market": "US",
     "aliases": ["palo alto"]},
    {"id": "cibr", "type": "asset", "label": "Cybersecurity ETF", "symbol": "CIBR", "market": "US"},
    # ------------- assets: HK / China -------------
    {"id": "tencent", "type": "asset", "label": "Tencent", "symbol": "0700.HK", "market": "HK",
     "aliases": ["700.HK", "wechat"]},
    {"id": "baba", "type": "asset", "label": "Alibaba", "symbol": "9988.HK", "market": "HK",
     "aliases": ["alibaba", "taobao"]},
    {"id": "meituan", "type": "asset", "label": "Meituan", "symbol": "3690.HK", "market": "HK"},
    {"id": "byd", "type": "asset", "label": "BYD", "symbol": "1211.HK", "market": "HK"},
    {"id": "icbc", "type": "asset", "label": "ICBC", "symbol": "1398.HK", "market": "HK",
     "aliases": ["601398.SS", "industrial and commercial bank"]},
    {"id": "moutai", "type": "asset", "label": "Kweichow Moutai", "symbol": "600519.SS",
     "market": "CN", "aliases": ["moutai", "kweichow"]},
    {"id": "catl", "type": "asset", "label": "CATL", "symbol": "300750.SZ", "market": "CN",
     "aliases": ["contemporary amperex"]},
    {"id": "trackerfund", "type": "asset", "label": "Tracker Fund (HSI)", "symbol": "2800.HK",
     "market": "HK", "aliases": ["hang seng index", "hsi"]},
    # ------------- assets: Singapore -------------
    {"id": "dbs", "type": "asset", "label": "DBS", "symbol": "D05.SI", "market": "SG",
     "aliases": ["D05.SG", "dbs bank"]},
    {"id": "ocbc", "type": "asset", "label": "OCBC", "symbol": "O39.SI", "market": "SG",
     "aliases": ["O39.SG"]},
    {"id": "uob", "type": "asset", "label": "UOB", "symbol": "U11.SI", "market": "SG",
     "aliases": ["U11.SG", "united overseas bank"]},
    {"id": "sti_etf", "type": "asset", "label": "STI ETF", "symbol": "ES3.SI", "market": "SG",
     "aliases": ["straits times index"]},
    {"id": "cict", "type": "asset", "label": "CapitaLand Integrated Commercial Trust",
     "symbol": "C38U.SI", "market": "SG", "aliases": ["capitaland", "cict"]},
    # ------------- assets: crypto -------------
    {"id": "btc", "type": "asset", "label": "Bitcoin", "symbol": "BTC/USD", "market": "CRYPTO",
     "aliases": ["btc"]},
    {"id": "eth", "type": "asset", "label": "Ethereum", "symbol": "ETH/USD", "market": "CRYPTO",
     "aliases": ["eth", "ether"]},
    {"id": "sol", "type": "asset", "label": "Solana", "symbol": "SOL/USD", "market": "CRYPTO",
     "aliases": ["sol"]},
]

SEED_EDGES = [
    # ---- factor -> factor (the macro field itself) ----
    {"src": "us_inflation", "dst": "fed_rate", "type": "influences", "sign": 1, "weight": 0.8,
     "note": "hot inflation forces hikes / delays cuts"},
    {"src": "fed_rate", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "fed_rate", "dst": "usd_strength", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "fed_rate", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "fed_rate", "dst": "mas_policy", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "SG imports US rates via the SGD peg framework"},
    {"src": "us_10y_yield", "dst": "us_megacap_tech", "type": "influences", "sign": -1,
     "weight": 0.6, "note": "duration: long-dated cashflows discount harder"},
    {"src": "us_10y_yield", "dst": "sg_reits", "type": "influences", "sign": -1, "weight": 0.7,
     "note": "REIT financing costs + yield competition"},
    {"src": "us_10y_yield", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "real yields are gold's opportunity cost"},
    {"src": "usd_strength", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "usd_strength", "dst": "copper_price", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "usd_strength", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "usd_strength", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "strong USD = EM outflows"},
    {"src": "risk_appetite", "dst": "crypto_liquidity", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "risk_appetite", "dst": "us_megacap_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "risk_appetite", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "risk_appetite", "dst": "consumer_staples", "type": "influences", "sign": -1,
     "weight": 0.4, "note": "defensives outperform when risk appetite falls"},
    {"src": "global_growth", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "global_growth", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "global_growth", "dst": "risk_appetite", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "oil_price", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.6,
     "delay_days": 30, "note": "pump prices feed CPI with ~a month lag"},
    {"src": "oil_price", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "geopolitical_tension", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "geopolitical_tension", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "geopolitical_tension", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "yen_carry", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "BOJ tightening (node up) unwinds carry -> global risk-off"},
    {"src": "opec", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.7,
     "note": "supply cuts (actor acting) lift price"},
    # ---- world-systems additions: liquidity, credit, real economy, τ-lags ----
    {"src": "fed_rate", "dst": "money_supply", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "hikes + QT drain liquidity"},
    {"src": "fed_rate", "dst": "global_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "delay_days": 120, "note": "monetary policy hits the real economy with long lags"},
    {"src": "fed_rate", "dst": "credit_conditions", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "money_supply", "dst": "risk_appetite", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "money_supply", "dst": "crypto_liquidity", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "money_supply", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "money_supply", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.4,
     "delay_days": 180, "note": "monetary inflation is the slowest cascade in the field"},
    {"src": "us_gov_debt", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "issuance supply pressures the long end"},
    {"src": "us_gov_debt", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "credit_conditions", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.6,
     "delay_days": 60, "note": "a crunch chokes activity ~a quarter later"},
    {"src": "credit_conditions", "dst": "us_financials", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "bank stress = credit down = financials down"},
    {"src": "us_employment", "dst": "us_consumer", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "us_employment", "dst": "fed_rate", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "hot labor keeps policy hawkish"},
    {"src": "us_consumer", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_elections", "dst": "us_china_tariffs", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "campaign seasons escalate trade rhetoric"},
    {"src": "us_elections", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.2},
    {"src": "sanctions", "dst": "geopolitical_tension", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "sanctions", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "energy sanctions constrain supply"},
    {"src": "shipping_costs", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.5,
     "delay_days": 45},
    {"src": "shipping_costs", "dst": "global_growth", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "geopolitical_tension", "dst": "shipping_costs", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "chokepoint risk (Red Sea, Hormuz) reroutes trade"},
    {"src": "us_china_tariffs", "dst": "rare_earths", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "escalation triggers China's export-curb counter-lever"},
    {"src": "china_government", "dst": "rare_earths", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "rare_earths", "dst": "semis", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "rare_earths", "dst": "ev_supply_chain", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "rare_earths", "dst": "defense_industry", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "natural_gas", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.3,
     "delay_days": 30},
    {"src": "natural_gas", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "ai_capex_cycle", "dst": "power_demand", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "power_demand", "dst": "natural_gas", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "power_demand", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "geopolitical_tension", "dst": "defense_spending", "type": "influences", "sign": 1,
     "weight": 0.6, "delay_days": 90, "note": "budget cycles ratchet slowly"},
    {"src": "defense_spending", "dst": "defense_industry", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "us_10y_yield", "dst": "us_financials", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "steeper curve helps NIMs (to a point)"},
    # ---- global coverage wiring (seed v3) ----
    {"src": "ecb_policy", "dst": "europe_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "delay_days": 90},
    {"src": "ecb_policy", "dst": "usd_strength", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "ECB hikes strengthen EUR = weaker DXY"},
    {"src": "europe_growth", "dst": "europe_equities", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "europe_growth", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "natural_gas", "dst": "europe_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "energy-price shocks hit Europe hardest"},
    {"src": "yen_carry", "dst": "japan_equities", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "BOJ tightening = stronger yen = exporters down"},
    {"src": "global_growth", "dst": "japan_equities", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "global_growth", "dst": "india_growth", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "oil_price", "dst": "india_growth", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "India is a large net oil importer"},
    {"src": "india_growth", "dst": "india_equities", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "usd_strength", "dst": "em_flows", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "em_flows", "dst": "india_equities", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "em_flows", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "em_flows", "dst": "sg_banks", "type": "influences", "sign": 1, "weight": 0.2},
    {"src": "us_government", "dst": "us_tech_regulation", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_tech_regulation", "dst": "us_megacap_tech", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "us_government", "dst": "crypto_regulation", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "crypto_regulation", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "tightening chokes flows; approvals (node down) unlock them"},
    {"src": "oil_supply", "dst": "oil_price", "type": "influences", "sign": -1, "weight": 0.7},
    {"src": "opec", "dst": "oil_supply", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "OPEC 'acting' = cutting quotas = fewer barrels"},
    {"src": "sanctions", "dst": "oil_supply", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "agri_food", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.3,
     "delay_days": 60},
    {"src": "agri_food", "dst": "china_consumer", "type": "influences", "sign": -1, "weight": 0.2},
    {"src": "vgk", "dst": "europe_equities", "type": "member_of", "weight": 0.9},
    {"src": "ewj", "dst": "japan_equities", "type": "member_of", "weight": 0.9},
    {"src": "inda", "dst": "india_equities", "type": "member_of", "weight": 0.9},
    {"src": "dba", "dst": "agri_food", "type": "correlates_with", "sign": 1, "weight": 0.8},
    # ---- treasury market stress / japan debt / china & korea growth (seed v11) ----
    {"src": "us_gov_debt", "dst": "bond_stress", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "issuance overwhelm -> auctions tail"},
    {"src": "us_inflation", "dst": "bond_stress", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "bond_stress", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "term premium blowout"},
    {"src": "bond_stress", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "the risk-free rate IS the discount rate for everything"},
    {"src": "bond_stress", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "fiscal-doubt gold bid: gold up WITH yields is the fiscal-crisis signature"},
    {"src": "japan_debt", "dst": "yen_carry", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "JGB stress forces BOJ normalization -> carry unwind"},
    {"src": "japan_debt", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "Japanese institutions repatriate FROM US Treasuries — the largest foreign holder"},
    {"src": "japan_debt", "dst": "bond_stress", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "china_stimulus", "dst": "china_growth", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "china_property", "dst": "china_growth", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_growth", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_growth", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_growth", "dst": "china_consumer", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "china_growth", "dst": "korea_growth", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "China is Korea's largest export market"},
    {"src": "ai_capex_cycle", "dst": "korea_growth", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "memory chips are ~20%% of Korean exports — Korea IS an AI-cycle amplifier"},
    {"src": "global_growth", "dst": "korea_growth", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "em_flows", "dst": "korea_equities", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "korea_growth", "dst": "korea_equities", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "geopolitical_tension", "dst": "korea_equities", "type": "influences", "sign": -1,
     "weight": 0.2, "note": "peninsula risk discount"},
    {"src": "samsung", "dst": "korea_equities", "type": "member_of", "weight": 0.9,
     "note": "~a quarter of the KOSPI by itself"},
    {"src": "skhynix", "dst": "korea_equities", "type": "member_of", "weight": 0.8},
    {"src": "ewy", "dst": "korea_equities", "type": "member_of", "weight": 0.9},
    {"src": "samsung", "dst": "semis", "type": "member_of", "weight": 0.8},
    {"src": "samsung", "dst": "hardware_chain", "type": "member_of", "weight": 0.7},
    {"src": "samsung", "dst": "nvda", "type": "supplies", "weight": 0.3, "weight_rev": 0.2,
     "note": "HBM third source"},
    {"src": "samsung", "dst": "aapl", "type": "supplies", "weight": 0.3, "weight_rev": 0.2,
     "note": "displays + memory"},
    {"src": "samsung", "dst": "tsmc", "type": "competes_with", "weight": 0.3,
     "note": "foundry race"},
    {"src": "samsung", "dst": "skhynix", "type": "competes_with", "weight": 0.4,
     "note": "memory duopoly"},
    # ---- US<->China policy ----
    {"src": "us_china_tariffs", "dst": "geopolitical_tension", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_china_tariffs", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "us_china_tariffs", "dst": "ev_supply_chain", "type": "influences", "sign": -1,
     "weight": 0.6, "note": "CATL/BYD overseas expansion risk"},
    {"src": "us_china_tariffs", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.4,
     "delay_days": 45, "note": "tariffs reach shelf prices over ~6 weeks"},
    {"src": "china_export_controls", "dst": "semis", "type": "influences", "sign": -1, "weight": 0.7,
     "note": "China revenue haircut for NVDA et al"},
    {"src": "china_export_controls", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "us_government", "dst": "us_china_tariffs", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "us_government", "dst": "china_export_controls", "type": "influences", "sign": 1, "weight": 0.8},
    # ---- China cluster ----
    {"src": "pboc_rate", "dst": "china_financials", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "rate CUTS (node down) compress bank NIMs -> banks down"},
    {"src": "pboc_rate", "dst": "china_property", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "cuts support property"},
    {"src": "china_government", "dst": "china_stimulus", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "china_government", "dst": "china_anti_corruption", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_stimulus", "dst": "china_consumer", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_stimulus", "dst": "china_property", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "china_stimulus", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_stimulus", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_property", "dst": "china_financials", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "property NPLs sit on bank balance sheets"},
    {"src": "china_property", "dst": "china_consumer", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "wealth effect"},
    {"src": "china_consumer", "dst": "china_staples", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_consumer", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_anti_corruption", "dst": "china_staples", "type": "influences", "sign": -1,
     "weight": 0.7, "note": "gifting/banquet demand collapses in campaigns (Moutai)"},
    {"src": "lithium_price", "dst": "ev_supply_chain", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "cheap lithium helps battery/EV margins"},
    {"src": "ai_capex_cycle", "dst": "semis", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "ai_capex_cycle", "dst": "ai_datacenter", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "ai_capex_cycle", "dst": "us_megacap_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "mas_policy", "dst": "sg_banks", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "higher SG rates -> NIM tailwind"},
    {"src": "mas_policy", "dst": "sg_reits", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "crypto_liquidity", "dst": "crypto_majors", "type": "influences", "sign": 1, "weight": 0.8},
    # ---- how the world reaches crypto (seed v9) ----
    {"src": "us_10y_yield", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "real yields are the opportunity cost of a zero-yield asset"},
    {"src": "yen_carry", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "carry unwinds hit the most liquid 24/7 risk asset FIRST"},
    {"src": "crypto_adoption", "dst": "crypto_liquidity", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "crypto_adoption", "dst": "crypto_majors", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "crypto_regulation", "dst": "crypto_adoption", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "approvals (regulation node DOWN) unlock the institutional wave"},
    {"src": "sanctions", "dst": "crypto_adoption", "type": "influences", "sign": 1, "weight": 0.2,
     "note": "capital flight / sanctions-evasion demand — crypto's gold-like bid"},
    {"src": "us_inflation", "dst": "crypto_adoption", "type": "influences", "sign": 1, "weight": 0.2,
     "note": "debasement narrative recruits marginal buyers (weak but real)"},
    {"src": "btc_halving", "dst": "crypto_majors", "type": "influences", "sign": 1, "weight": 0.3,
     "delay_days": 60, "note": "supply squeeze transmits slowly, narrative faster"},
    {"src": "power_demand", "dst": "btc_halving", "type": "influences", "sign": -1, "weight": 0.2,
     "note": "power costs squeeze miners post-halving (capitulation risk)"},
    {"src": "crypto_liquidity", "dst": "coin", "type": "influences", "sign": 1, "weight": 0.7,
     "note": "exchange revenue IS volume x volatility"},
    {"src": "crypto_regulation", "dst": "coin", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "the regulated on-ramp carries the direct policy risk"},
    {"src": "mstr", "dst": "btc", "type": "owns", "weight": 0.9,
     "note": "treasury is ~all BTC — trades as leveraged bitcoin"},
    {"src": "coin", "dst": "crypto_majors", "type": "member_of", "weight": 0.5,
     "note": "the equity beta to the asset class"},
    # ---- membership (asset -> theme; shocks flow theme -> members) ----
    {"src": "aapl", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.8},
    {"src": "msft", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.8},
    {"src": "msft", "dst": "ai_datacenter", "type": "member_of", "weight": 0.6},
    {"src": "nvda", "dst": "semis", "type": "member_of", "weight": 0.9},
    {"src": "nvda", "dst": "ai_datacenter", "type": "member_of", "weight": 0.9},
    {"src": "tsla", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.8},
    {"src": "xlk", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.9},
    {"src": "xle", "dst": "energy_sector", "type": "member_of", "weight": 0.9},
    {"src": "xlp", "dst": "consumer_staples", "type": "member_of", "weight": 0.9},
    {"src": "tencent", "dst": "china_tech", "type": "member_of", "weight": 0.9},
    {"src": "baba", "dst": "china_tech", "type": "member_of", "weight": 0.9},
    {"src": "meituan", "dst": "china_tech", "type": "member_of", "weight": 0.8},
    {"src": "byd", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.8},
    {"src": "byd", "dst": "china_tech", "type": "member_of", "weight": 0.4},
    {"src": "icbc", "dst": "china_financials", "type": "member_of", "weight": 0.9},
    {"src": "moutai", "dst": "china_staples", "type": "member_of", "weight": 0.9},
    {"src": "catl", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.9},
    {"src": "trackerfund", "dst": "china_tech", "type": "member_of", "weight": 0.5},
    {"src": "trackerfund", "dst": "china_financials", "type": "member_of", "weight": 0.5},
    {"src": "dbs", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "ocbc", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "uob", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "sti_etf", "dst": "sg_banks", "type": "member_of", "weight": 0.6,
     "note": "STI is ~half bank weight"},
    {"src": "cict", "dst": "sg_reits", "type": "member_of", "weight": 0.9},
    {"src": "btc", "dst": "crypto_majors", "type": "member_of", "weight": 0.9},
    {"src": "eth", "dst": "crypto_majors", "type": "member_of", "weight": 0.9},
    {"src": "sol", "dst": "crypto_majors", "type": "member_of", "weight": 0.8},
    # ---- supply / competition / proxies ----
    # supplies flows BOTH ways: supplier disruption hits the customer, customer
    # weakness hits the supplier — one shock moves the whole cluster.
    {"src": "catl", "dst": "tsla", "type": "supplies", "weight": 0.5, "weight_rev": 0.4,
     "note": "battery supplier relationship"},
    {"src": "tsmc", "dst": "nvda", "type": "supplies", "weight": 0.7, "weight_rev": 0.35,
     "note": "sole leading-edge foundry for Nvidia GPUs"},
    {"src": "tsmc", "dst": "aapl", "type": "supplies", "weight": 0.5, "weight_rev": 0.3,
     "note": "all iPhone A-series/M-series silicon"},
    {"src": "tsmc", "dst": "amd", "type": "supplies", "weight": 0.6},
    {"src": "asml", "dst": "tsmc", "type": "supplies", "weight": 0.6, "weight_rev": 0.35,
     "note": "EUV monopoly — no ASML, no leading edge"},
    {"src": "skhynix", "dst": "nvda", "type": "supplies", "weight": 0.6, "weight_rev": 0.4,
     "note": "primary HBM memory supplier"},
    {"src": "micron", "dst": "nvda", "type": "supplies", "weight": 0.4,
     "note": "HBM second source"},
    {"src": "foxconn", "dst": "aapl", "type": "supplies", "weight": 0.7, "weight_rev": 0.5,
     "note": "iPhone assembly"},
    {"src": "sunny", "dst": "aapl", "type": "supplies", "weight": 0.3,
     "note": "camera modules"},
    {"src": "ganfeng", "dst": "catl", "type": "supplies", "weight": 0.5, "weight_rev": 0.35,
     "note": "lithium feedstock"},
    {"src": "ganfeng", "dst": "byd", "type": "supplies", "weight": 0.4},
    {"src": "skhynix", "dst": "micron", "type": "competes_with", "weight": 0.4,
     "note": "HBM share war"},
    {"src": "amd", "dst": "nvda", "type": "competes_with", "weight": 0.4},
    # supply-chain memberships + cluster drivers
    {"src": "tsmc", "dst": "semis", "type": "member_of", "weight": 0.9},
    {"src": "tsmc", "dst": "hardware_chain", "type": "member_of", "weight": 0.9},
    {"src": "asml", "dst": "semis", "type": "member_of", "weight": 0.8},
    {"src": "asml", "dst": "hardware_chain", "type": "member_of", "weight": 0.8},
    {"src": "amd", "dst": "semis", "type": "member_of", "weight": 0.9},
    {"src": "amd", "dst": "ai_datacenter", "type": "member_of", "weight": 0.7},
    {"src": "micron", "dst": "semis", "type": "member_of", "weight": 0.8},
    {"src": "skhynix", "dst": "semis", "type": "member_of", "weight": 0.8},
    {"src": "foxconn", "dst": "hardware_chain", "type": "member_of", "weight": 0.9},
    {"src": "sunny", "dst": "hardware_chain", "type": "member_of", "weight": 0.7},
    {"src": "sunny", "dst": "china_tech", "type": "member_of", "weight": 0.4},
    {"src": "ganfeng", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.7},
    {"src": "lithium_price", "dst": "ganfeng", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "the miner is the INVERSE of battery makers on lithium price"},
    {"src": "geopolitical_tension", "dst": "tsmc", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "Taiwan-strait risk discount"},
    {"src": "geopolitical_tension", "dst": "foxconn", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "us_china_tariffs", "dst": "hardware_chain", "type": "influences", "sign": -1,
     "weight": 0.4, "note": "tariffs tax every cross-strait component hop"},
    # robotics
    {"src": "ai_capex_cycle", "dst": "robotics", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "AI capability spills into embodied automation"},
    {"src": "global_growth", "dst": "robotics", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "capex-cyclical: factories buy robots when demand is strong"},
    {"src": "us_employment", "dst": "robotics", "type": "influences", "sign": -1, "weight": 0.2,
     "note": "labor scarcity (employment tight/costly) accelerates automation"},
    {"src": "fanuc", "dst": "robotics", "type": "member_of", "weight": 0.9},
    {"src": "fanuc", "dst": "japan_equities", "type": "member_of", "weight": 0.5},
    {"src": "ubtech", "dst": "robotics", "type": "member_of", "weight": 0.8},
    {"src": "ubtech", "dst": "china_tech", "type": "member_of", "weight": 0.4},
    {"src": "botz", "dst": "robotics", "type": "member_of", "weight": 0.9},
    {"src": "tsla", "dst": "robotics", "type": "member_of", "weight": 0.3,
     "note": "Optimus humanoid program"},
    {"src": "nvda", "dst": "robotics", "type": "member_of", "weight": 0.3,
     "note": "robot brains run on their silicon"},
    # ---- raw materials, miners, energy transition ----
    {"src": "global_growth", "dst": "nickel_price", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "nickel_price", "dst": "ev_supply_chain", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "battery cathode input cost"},
    {"src": "nickel_price", "dst": "vale", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "global_growth", "dst": "vale", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "iron ore is a pure global-construction bet"},
    {"src": "gold_price", "dst": "silver_price", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "monetary-metal beta"},
    {"src": "energy_transition", "dst": "silver_price", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "solar paste is a big silver sink"},
    {"src": "silver_price", "dst": "solar", "type": "influences", "sign": -1, "weight": 0.2,
     "note": "input cost squeeze on panel makers"},
    {"src": "gold_price", "dst": "gdx", "type": "influences", "sign": 1, "weight": 0.8,
     "note": "miners are leveraged gold"},
    {"src": "gold_price", "dst": "zijin", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "copper_price", "dst": "zijin", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "lithium_price", "dst": "alb", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "same inverse-of-battery-makers logic as Ganfeng"},
    {"src": "power_demand", "dst": "uranium_price", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "nuclear restart wave for datacenter power"},
    {"src": "uranium_price", "dst": "cameco", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "energy_transition", "dst": "solar", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "energy_transition", "dst": "uranium_price", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "energy_transition", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "electrification is copper-hungry"},
    {"src": "energy_transition", "dst": "oil_price", "type": "influences", "sign": -1, "weight": 0.2,
     "delay_days": 180, "note": "demand substitution is slow"},
    {"src": "china_government", "dst": "energy_transition", "type": "influences", "sign": 1,
     "weight": 0.4, "note": "China dominates solar/battery supply"},
    {"src": "us_government", "dst": "energy_transition", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "subsidy regimes swing with administrations — sign flips via polarity"},
    {"src": "fslr", "dst": "solar", "type": "member_of", "weight": 0.9},
    {"src": "jks", "dst": "solar", "type": "member_of", "weight": 0.9},
    {"src": "longi", "dst": "solar", "type": "member_of", "weight": 0.9},
    {"src": "tan", "dst": "solar", "type": "member_of", "weight": 0.9},
    {"src": "us_china_tariffs", "dst": "jks", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "Chinese panels lose US market access"},
    {"src": "us_china_tariffs", "dst": "longi", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "us_china_tariffs", "dst": "fslr", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "the DOMESTIC producer BENEFITS from panel tariffs — signs differ within one theme"},
    {"src": "alb", "dst": "miners", "type": "member_of", "weight": 0.8},
    {"src": "gdx", "dst": "miners", "type": "member_of", "weight": 0.8},
    {"src": "zijin", "dst": "miners", "type": "member_of", "weight": 0.8},
    {"src": "vale", "dst": "miners", "type": "member_of", "weight": 0.8},
    {"src": "cameco", "dst": "miners", "type": "member_of", "weight": 0.7},
    {"src": "ganfeng", "dst": "miners", "type": "member_of", "weight": 0.7},
    {"src": "mp", "dst": "miners", "type": "member_of", "weight": 0.7},
    {"src": "rare_earths", "dst": "mp", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "China export curbs make the ex-China producer MORE valuable"},
    {"src": "mp", "dst": "defense_industry", "type": "member_of", "weight": 0.3,
     "note": "magnets for defense supply chains"},
    {"src": "intc", "dst": "semis", "type": "member_of", "weight": 0.7},
    {"src": "intc", "dst": "hardware_chain", "type": "member_of", "weight": 0.5},
    # ---- the AI money circle (detectable: owns + supplies the same party) ----
    {"src": "nvda", "dst": "crwv", "type": "owns", "weight": 0.1,
     "note": "equity stake in a customer"},
    {"src": "nvda", "dst": "crwv", "type": "supplies", "weight": 0.7, "weight_rev": 0.3,
     "note": "the stake's recipient spends it on GPUs — capital out as investment, back as revenue"},
    {"src": "crwv", "dst": "ai_datacenter", "type": "member_of", "weight": 0.8},
    {"src": "ai_circularity", "dst": "ai_capex_cycle", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "when the circle gets exposed/questioned, the capex growth story deflates"},
    {"src": "ai_circularity", "dst": "crwv", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "the financed party takes the direct hit"},
    # ---- government influence (state ownership / golden shares) ----
    {"src": "intc", "dst": "us_government", "type": "regulated_by", "weight": 0.4,
     "note": "US gov equity stake + CHIPS Act: policy IS a fundamental here"},
    {"src": "mp", "dst": "us_government", "type": "regulated_by", "weight": 0.5,
     "note": "DoD stake + price floor deal — a policy-backed company"},
    {"src": "icbc", "dst": "china_government", "type": "regulated_by", "weight": 0.6,
     "note": "state-owned bank: lends where told, NIM is a policy variable"},
    {"src": "moutai", "dst": "china_government", "type": "regulated_by", "weight": 0.5,
     "note": "Guizhou province is the controlling shareholder"},
    {"src": "crbeer", "dst": "china_government", "type": "regulated_by", "weight": 0.4,
     "note": "China Resources is an SOE conglomerate"},
    # cybersecurity
    {"src": "geopolitical_tension", "dst": "cybersecurity", "type": "influences", "sign": 1,
     "weight": 0.4, "note": "state-sponsored attacks rise with tension — cyber names benefit"},
    {"src": "ai_capex_cycle", "dst": "cybersecurity", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "AI attack surface + AI-powered defense spend"},
    {"src": "us_government", "dst": "cybersecurity", "type": "influences", "sign": 1, "weight": 0.2,
     "note": "federal cyber mandates"},
    {"src": "crwd", "dst": "cybersecurity", "type": "member_of", "weight": 0.9},
    {"src": "panw", "dst": "cybersecurity", "type": "member_of", "weight": 0.9},
    {"src": "cibr", "dst": "cybersecurity", "type": "member_of", "weight": 0.9},
    {"src": "crwd", "dst": "panw", "type": "competes_with", "weight": 0.3},
    {"src": "byd", "dst": "tsla", "type": "competes_with", "weight": 0.4},
    {"src": "gld", "dst": "gold_price", "type": "correlates_with", "sign": 1, "weight": 0.9},
    {"src": "uso", "dst": "oil_price", "type": "correlates_with", "sign": 1, "weight": 0.9},
    # ---- consumer brands & consumables (seed v4) ----
    {"src": "china_consumer", "dst": "global_luxury", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "Chinese buyers are ~a third of global luxury demand"},
    {"src": "china_anti_corruption", "dst": "global_luxury", "type": "influences", "sign": -1,
     "weight": 0.5, "note": "gifting crackdowns hit luxury like they hit baijiu"},
    {"src": "china_consumer", "dst": "sportswear", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "Anta/Li-Ning direct; Nike/adidas China sales"},
    {"src": "us_consumer", "dst": "sportswear", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "us_china_tariffs", "dst": "sportswear", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "supply chains + nationalist boycott risk both ways"},
    {"src": "us_consumer", "dst": "food_beverage", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "china_consumer", "dst": "food_beverage", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "agri_food", "dst": "food_beverage", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "input-cost squeeze on packaged food margins"},
    {"src": "risk_appetite", "dst": "healthcare", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "defensive: outperforms when risk appetite falls"},
    {"src": "us_government", "dst": "healthcare", "type": "influences", "sign": -1, "weight": 0.2,
     "note": "drug-pricing policy risk"},
    {"src": "lvmh", "dst": "global_luxury", "type": "member_of", "weight": 0.9},
    {"src": "prada", "dst": "global_luxury", "type": "member_of", "weight": 0.8},
    {"src": "moutai", "dst": "global_luxury", "type": "member_of", "weight": 0.4,
     "note": "baijiu is China's own luxury-gifting proxy"},
    {"src": "nike", "dst": "sportswear", "type": "member_of", "weight": 0.9},
    {"src": "adidas", "dst": "sportswear", "type": "member_of", "weight": 0.9},
    {"src": "anta", "dst": "sportswear", "type": "member_of", "weight": 0.9},
    {"src": "lining", "dst": "sportswear", "type": "member_of", "weight": 0.9},
    {"src": "xlv", "dst": "healthcare", "type": "member_of", "weight": 0.9},
    {"src": "jnj", "dst": "healthcare", "type": "member_of", "weight": 0.9},
    {"src": "ko", "dst": "food_beverage", "type": "member_of", "weight": 0.9},
    {"src": "nongfu", "dst": "food_beverage", "type": "member_of", "weight": 0.9},
    {"src": "mcd", "dst": "food_beverage", "type": "member_of", "weight": 0.9},
    {"src": "sbux", "dst": "food_beverage", "type": "member_of", "weight": 0.8},
    {"src": "china_consumer", "dst": "china_fnb", "type": "influences", "sign": 1, "weight": 0.7,
     "note": "mass-market spending is the whole story for tea/hotpot/toys"},
    {"src": "yumchina", "dst": "china_fnb", "type": "member_of", "weight": 0.9},
    {"src": "mixue", "dst": "china_fnb", "type": "member_of", "weight": 0.9},
    {"src": "haidilao", "dst": "china_fnb", "type": "member_of", "weight": 0.9},
    {"src": "popmart", "dst": "china_fnb", "type": "member_of", "weight": 0.8},
    {"src": "nongfu", "dst": "china_fnb", "type": "member_of", "weight": 0.6},
    {"src": "sbux", "dst": "china_fnb", "type": "member_of", "weight": 0.3,
     "note": "meaningful China store base"},
    {"src": "agri_food", "dst": "china_fnb", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "food input costs squeeze restaurant margins"},
    {"src": "luckin", "dst": "china_fnb", "type": "member_of", "weight": 0.9},
    {"src": "crbeer", "dst": "china_fnb", "type": "member_of", "weight": 0.7},
    {"src": "crbeer", "dst": "food_beverage", "type": "member_of", "weight": 0.5},
    {"src": "mengniu", "dst": "food_beverage", "type": "member_of", "weight": 0.8},
    {"src": "mengniu", "dst": "china_fnb", "type": "member_of", "weight": 0.5},
    {"src": "unipres", "dst": "food_beverage", "type": "member_of", "weight": 0.8},
    {"src": "unipres", "dst": "china_fnb", "type": "member_of", "weight": 0.5},
    {"src": "luckin", "dst": "sbux", "type": "competes_with", "weight": 0.4,
     "note": "the China coffee war"},
    {"src": "agri_food", "dst": "mengniu", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "raw milk / feed costs"},
    # ---- ownership: follow the money (weight = stake's share of the OWNER) ----
    {"src": "prosus", "dst": "tencent", "type": "owns", "weight": 0.8,
     "note": "~24% of Tencent IS most of Prosus's NAV"},
    {"src": "tencent", "dst": "pdd", "type": "owns", "weight": 0.25,
     "note": "long-held strategic stake (~15%)"},
    {"src": "tencent", "dst": "sea", "type": "owns", "weight": 0.2,
     "note": "strategic stake in Sea (Shopee)"},
    {"src": "softbank", "dst": "arm", "type": "owns", "weight": 0.8,
     "note": "~88% — SoftBank trades like leveraged Arm"},
    {"src": "berkshire", "dst": "aapl", "type": "owns", "weight": 0.4,
     "note": "largest equity holding"},
    {"src": "berkshire", "dst": "ko", "type": "owns", "weight": 0.15,
     "note": "~9% of Coca-Cola, decades-held"},
    {"src": "temasek", "dst": "dbs", "type": "owns", "weight": 0.4,
     "note": "~29% anchor shareholder"},
    {"src": "pdd", "dst": "china_tech", "type": "member_of", "weight": 0.8},
    {"src": "sea", "dst": "china_tech", "type": "member_of", "weight": 0.4,
     "note": "SEA-region internet, HK/China beta"},
    {"src": "arm", "dst": "semis", "type": "member_of", "weight": 0.8},
    {"src": "arm", "dst": "ai_datacenter", "type": "member_of", "weight": 0.6},
    {"src": "softbank", "dst": "japan_equities", "type": "member_of", "weight": 0.6},
    {"src": "ai_capex_cycle", "dst": "softbank", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "Vision Fund is a leveraged AI-cycle bet"},
    {"src": "prosus", "dst": "europe_equities", "type": "member_of", "weight": 0.3},
    {"src": "berkshire", "dst": "us_financials", "type": "member_of", "weight": 0.5},
    {"src": "pdd", "dst": "baba", "type": "competes_with", "weight": 0.5,
     "note": "e-commerce share war"},
    {"src": "xlf", "dst": "us_financials", "type": "member_of", "weight": 0.9},
    {"src": "ita", "dst": "defense_industry", "type": "member_of", "weight": 0.9},
    {"src": "tlt", "dst": "us_10y_yield", "type": "correlates_with", "sign": -1, "weight": 0.9,
     "note": "yields up = long-bond prices down"},
]
