"""Curated seed for the knowledge graph.

This is the hand-authored, high-precision starting wiring: macro factors with
their stable points, policy actors, themes/sectors, and a multi-market asset
universe (US / HK / China A / Singapore / crypto — all reachable via Longbridge
or yfinance). LLM-proposed edges get appended on top over time with provenance;
they never replace these.

Sign convention: node "value" going UP means the named quantity rises (a rate
node up = tightening; a tension node up = more tension). Edge sign +1 means the
destination moves the same way as the source. `delay_days` on an edge is the
world-systems τ: the effect lands that many days later via the field's pending
queue, not in the same cycle.

Bump SEED_VERSION whenever curated nodes/edges change — existing
knowledge_graph.json files merge the update in on next load (LLM-proposed edges
are preserved).
"""

SEED_VERSION = 3

SEED_NODES = [
    # ------------- macro factors (with stable points) -------------
    {"id": "fed_rate", "type": "factor", "label": "Fed policy rate",
     "aliases": ["federal reserve", "fed", "fomc", "us interest rate", "rate hike", "rate cut"],
     "equilibrium": "neutral ~3%; far above = restrictive, cuts loom; far below = stimulative"},
    {"id": "us_inflation", "type": "factor", "label": "US inflation",
     "aliases": ["cpi", "inflation", "pce"],
     "equilibrium": "Fed target 2% yoy; >3% forces hawkishness, <2% permits easing"},
    {"id": "us_10y_yield", "type": "factor", "label": "US 10Y yield",
     "aliases": ["treasury yield", "10-year", "long rates", "bond yields"],
     "equilibrium": "3.5-4.5% consistent with 2% inflation + real growth"},
    {"id": "usd_strength", "type": "factor", "label": "US dollar",
     "aliases": ["dollar index", "dxy", "greenback", "dollar"],
     "equilibrium": "DXY ~95-105; strong USD tightens global liquidity"},
    {"id": "risk_appetite", "type": "factor", "label": "Global risk appetite",
     "aliases": ["risk-on", "risk-off", "vix", "volatility", "market fear"],
     "equilibrium": "VIX 12-20 = calm; >25 = fear; <12 = complacency (fragile)"},
    {"id": "global_growth", "type": "factor", "label": "Global growth",
     "aliases": ["gdp growth", "recession", "pmi", "manufacturing activity", "soft landing"],
     "equilibrium": "global PMI ~50; below = contraction"},
    {"id": "oil_price", "type": "commodity", "label": "Crude oil",
     "aliases": ["brent", "wti", "crude", "opec cut", "oil supply"],
     "equilibrium": "$65-85 balances producers and consumers; >$95 is an inflation shock"},
    {"id": "gold_price", "type": "commodity", "label": "Gold",
     "aliases": ["bullion", "safe haven", "xau"],
     "equilibrium": "rises on real-rate falls, USD weakness, fear"},
    {"id": "copper_price", "type": "commodity", "label": "Copper",
     "aliases": ["industrial metals", "dr copper"],
     "equilibrium": "tracks China/global industrial demand; the growth bellwether"},
    {"id": "lithium_price", "type": "commodity", "label": "Lithium",
     "aliases": ["battery metals", "lithium carbonate"],
     "equilibrium": "boom-bust vs EV demand; low prices squeeze miners, help battery makers"},
    {"id": "ai_capex_cycle", "type": "factor", "label": "AI capex cycle",
     "aliases": ["ai spending", "datacenter buildout", "gpu demand", "ai bubble"],
     "equilibrium": "hyperscaler capex growth >0; a guidance cut from any mega-cap cracks it"},
    {"id": "crypto_liquidity", "type": "factor", "label": "Crypto liquidity",
     "aliases": ["etf inflows", "stablecoin supply", "crypto flows", "bitcoin etf"],
     "equilibrium": "follows global liquidity + risk appetite; halving cycles overlay"},
    {"id": "geopolitical_tension", "type": "factor", "label": "Geopolitical tension",
     "aliases": ["war", "conflict", "taiwan strait", "middle east", "strait of hormuz"],
     "equilibrium": "baseline simmer; escalation lifts oil/gold, sinks risk appetite"},
    {"id": "us_china_tariffs", "type": "factor", "label": "US-China trade policy",
     "aliases": ["tariff", "trade war", "trade deal", "export tariffs", "decoupling"],
     "equilibrium": "managed friction; escalation hits supply chains + China exporters"},
    {"id": "china_export_controls", "type": "factor", "label": "Chip export controls",
     "aliases": ["chip ban", "semiconductor restrictions", "entity list", "chip curbs"],
     "equilibrium": "tightening trend; each round reprices AI/semi China revenue"},
    # ------------- world-systems additions (liquidity, credit, real economy) -------------
    {"id": "money_supply", "type": "factor", "label": "Global liquidity / money supply",
     "aliases": ["m2", "qe", "quantitative easing", "quantitative tightening", "liquidity injection", "balance sheet runoff"],
     "equilibrium": "expanding with nominal GDP; QT drains risk assets, QE floats them"},
    {"id": "us_gov_debt", "type": "factor", "label": "US government debt / fiscal",
     "aliases": ["deficit", "debt ceiling", "treasury auction", "treasury issuance", "credit rating downgrade", "fiscal deficit"],
     "equilibrium": "sustainable while demand absorbs issuance; failed auctions/downgrades reprice the long end"},
    {"id": "credit_conditions", "type": "factor", "label": "Credit availability / banking system",
     "aliases": ["credit crunch", "bank lending", "loan defaults", "credit spreads", "bank failure", "npl"],
     "equilibrium": "spreads tight, lending flowing; a crunch (node DOWN) chokes growth with a lag"},
    {"id": "us_employment", "type": "factor", "label": "US labor market",
     "aliases": ["payrolls", "nonfarm", "jobless claims", "layoffs", "unemployment rate", "job cuts"],
     "equilibrium": "unemployment ~4%; hot labor keeps the Fed hawkish, cracks precede recessions"},
    {"id": "us_consumer", "type": "factor", "label": "US consumer spending/confidence",
     "aliases": ["retail sales", "consumer confidence", "consumer spending", "holiday sales"],
     "equilibrium": "~70% of US GDP; rolls over when savings deplete and hiring stalls"},
    {"id": "us_elections", "type": "factor", "label": "US election cycle",
     "aliases": ["midterms", "election", "presidential race", "campaign"],
     "equilibrium": "quadrennial vol; policy promises move tariffs, regulation, deficits"},
    {"id": "sanctions", "type": "factor", "label": "Sanctions regime",
     "aliases": ["sanction", "embargo", "asset freeze", "secondary sanctions"],
     "equilibrium": "ratcheting tool of statecraft; new rounds hit energy flows and targeted sectors"},
    {"id": "shipping_costs", "type": "factor", "label": "Shipping / supply chains",
     "aliases": ["freight rates", "red sea", "suez", "panama canal", "container rates", "port congestion", "supply chain"],
     "equilibrium": "boring when normal; chokepoint disruptions feed inflation with ~1-2 month lag"},
    {"id": "rare_earths", "type": "factor", "label": "Critical minerals / rare earths",
     "aliases": ["rare earth", "gallium", "germanium", "graphite export", "critical minerals"],
     "equilibrium": "China's counter-lever in the trade war; export curbs squeeze chips/EV/defense"},
    {"id": "power_demand", "type": "factor", "label": "Electricity / datacenter power",
     "aliases": ["electricity demand", "power grid", "datacenter power", "uranium", "nuclear power", "power shortage"],
     "equilibrium": "AI buildout is power-constrained; shortages throttle datacenter growth"},
    {"id": "defense_spending", "type": "factor", "label": "Defense spending",
     "aliases": ["defense budget", "military spending", "rearmament", "nato spending"],
     "equilibrium": "ratchets up with tension (slowly, budget cycles), rarely back down"},
    {"id": "natural_gas", "type": "commodity", "label": "Natural gas",
     "aliases": ["lng", "natgas", "gas prices", "henry hub", "ttf"],
     "equilibrium": "regional markets linked by LNG; cold winters + outages spike it"},
    # ------------- China factor cluster -------------
    {"id": "pboc_rate", "type": "factor", "label": "PBOC policy rate",
     "aliases": ["pboc", "lpr", "china rate cut", "rrr cut", "people's bank of china"],
     "equilibrium": "easing bias while property deleverages; cuts squeeze bank NIMs"},
    {"id": "china_stimulus", "type": "factor", "label": "China fiscal stimulus",
     "aliases": ["china stimulus", "special bonds", "consumption vouchers", "politburo stimulus"],
     "equilibrium": "episodic; big packages lift consumer + property + commodities"},
    {"id": "china_property", "type": "factor", "label": "China property sector",
     "aliases": ["evergrande", "country garden", "china real estate", "home sales china"],
     "equilibrium": "still deleveraging; stabilization = major risk-on for China assets"},
    {"id": "china_consumer", "type": "factor", "label": "China consumer demand",
     "aliases": ["china retail sales", "china consumption", "singles day", "china spending"],
     "equilibrium": "soft since 2021; hostage to property wealth effect + confidence"},
    {"id": "china_anti_corruption", "type": "factor", "label": "China anti-corruption drive",
     "aliases": ["anti-corruption", "austerity campaign", "graft crackdown", "common prosperity"],
     "equilibrium": "recurring campaigns suppress luxury/baijiu gifting demand"},
    {"id": "yen_carry", "type": "factor", "label": "BOJ policy / yen carry",
     "aliases": ["boj", "bank of japan", "yen", "carry trade", "japan rate hike"],
     "equilibrium": "BOJ normalization unwinds carry trades -> global risk-off spasms"},
    {"id": "mas_policy", "type": "factor", "label": "MAS policy (SGD)",
     "aliases": ["mas", "monetary authority of singapore", "sgd neer", "singapore policy"],
     "equilibrium": "SGD appreciation path; SG rates import US rates -> bank NIMs, REIT costs"},
    # ------------- global coverage (seed v3) -------------
    {"id": "ecb_policy", "type": "factor", "label": "ECB policy",
     "aliases": ["ecb", "european central bank", "lagarde", "eurozone rates"],
     "equilibrium": "tracks eurozone inflation to 2%; divergence vs Fed moves EUR/USD"},
    {"id": "europe_growth", "type": "factor", "label": "Europe growth",
     "aliases": ["eurozone economy", "germany economy", "eu growth", "european recession"],
     "equilibrium": "structurally slow; energy shocks and China demand swing it"},
    {"id": "india_growth", "type": "factor", "label": "India growth",
     "aliases": ["india economy", "india gdp", "rbi", "modi economy"],
     "equilibrium": "fastest large economy; oil-import sensitive"},
    {"id": "em_flows", "type": "factor", "label": "EM capital flows",
     "aliases": ["emerging market flows", "em outflows", "foreign investors"],
     "equilibrium": "follow USD inversely; sudden stops hit all EM at once"},
    {"id": "us_tech_regulation", "type": "factor", "label": "US tech regulation",
     "aliases": ["antitrust", "ai regulation", "big tech probe", "ftc lawsuit"],
     "equilibrium": "simmering; a breakup ruling or AI act reprices mega-caps"},
    {"id": "crypto_regulation", "type": "factor", "label": "Crypto regulation (up = tightening)",
     "aliases": ["crypto crackdown", "stablecoin law", "etf approval", "sec crypto"],
     "equilibrium": "approvals (node DOWN) unlock flows; crackdowns choke liquidity"},
    {"id": "oil_supply", "type": "factor", "label": "Oil supply (up = more barrels)",
     "aliases": ["production increase", "shale output", "spare capacity", "oil glut"],
     "equilibrium": "OPEC discipline vs shale; gluts cap prices, outages spike them"},
    {"id": "agri_food", "type": "commodity", "label": "Food / agriculture prices",
     "aliases": ["wheat", "grain prices", "food prices", "harvest", "el nino"],
     "equilibrium": "weather + fertilizer + export bans; feeds EM inflation hardest"},
    # ------------- policy actors -------------
    {"id": "us_government", "type": "actor", "label": "US government",
     "aliases": ["white house", "congress", "us president", "treasury", "sec"]},
    {"id": "china_government", "type": "actor", "label": "China government",
     "aliases": ["beijing", "politburo", "state council", "xi jinping", "csrc"]},
    {"id": "opec", "type": "actor", "label": "OPEC+",
     "aliases": ["opec", "saudi arabia oil", "production quota"]},
    # ------------- themes / sectors -------------
    {"id": "us_megacap_tech", "type": "theme", "label": "US mega-cap tech",
     "aliases": ["magnificent seven", "big tech", "nasdaq"]},
    {"id": "semis", "type": "theme", "label": "Semiconductors",
     "aliases": ["chips", "semiconductor", "foundry", "chipmakers"]},
    {"id": "ai_datacenter", "type": "theme", "label": "AI / datacenter",
     "aliases": ["artificial intelligence", "datacenter", "gpu", "accelerators"]},
    {"id": "ev_supply_chain", "type": "theme", "label": "EV supply chain",
     "aliases": ["electric vehicle", "ev battery", "ev makers"]},
    {"id": "china_tech", "type": "theme", "label": "China internet/tech",
     "aliases": ["china tech", "kweb", "china internet", "hang seng tech"]},
    {"id": "china_financials", "type": "theme", "label": "China banks/financials",
     "aliases": ["china banks", "chinese lenders", "bank nim china"]},
    {"id": "china_staples", "type": "theme", "label": "China consumer staples/luxury",
     "aliases": ["baijiu", "china liquor", "china staples"]},
    {"id": "energy_sector", "type": "sector", "label": "Energy sector",
     "aliases": ["oil majors", "energy stocks"]},
    {"id": "consumer_staples", "type": "sector", "label": "Consumer staples (defensive)",
     "aliases": ["defensives", "staples"]},
    {"id": "sg_banks", "type": "theme", "label": "Singapore banks",
     "aliases": ["singapore banks", "sg lenders"]},
    {"id": "sg_reits", "type": "theme", "label": "Singapore REITs",
     "aliases": ["s-reits", "singapore reits"]},
    {"id": "crypto_majors", "type": "theme", "label": "Crypto majors",
     "aliases": ["cryptocurrency", "bitcoin", "digital assets"]},
    {"id": "europe_equities", "type": "theme", "label": "Europe equities",
     "aliases": ["dax", "stoxx", "european stocks"]},
    {"id": "japan_equities", "type": "theme", "label": "Japan equities",
     "aliases": ["nikkei", "topix", "japanese stocks"]},
    {"id": "india_equities", "type": "theme", "label": "India equities",
     "aliases": ["nifty", "sensex", "indian stocks"]},
    {"id": "us_financials", "type": "theme", "label": "US banks/financials",
     "aliases": ["us banks", "wall street banks", "regional banks"]},
    {"id": "defense_industry", "type": "theme", "label": "Defense industry",
     "aliases": ["defense stocks", "arms makers", "defense contractors"]},
    # ------------- assets: US -------------
    {"id": "aapl", "type": "asset", "label": "Apple", "symbol": "AAPL", "market": "US",
     "aliases": ["iphone"]},
    {"id": "msft", "type": "asset", "label": "Microsoft", "symbol": "MSFT", "market": "US",
     "aliases": ["azure"]},
    {"id": "nvda", "type": "asset", "label": "Nvidia", "symbol": "NVDA", "market": "US",
     "aliases": ["h100", "blackwell"]},
    {"id": "tsla", "type": "asset", "label": "Tesla", "symbol": "TSLA", "market": "US",
     "aliases": ["elon musk"]},
    {"id": "xlk", "type": "asset", "label": "Tech sector ETF", "symbol": "XLK", "market": "US"},
    {"id": "xle", "type": "asset", "label": "Energy sector ETF", "symbol": "XLE", "market": "US"},
    {"id": "xlp", "type": "asset", "label": "Staples sector ETF", "symbol": "XLP", "market": "US"},
    {"id": "gld", "type": "asset", "label": "Gold ETF", "symbol": "GLD", "market": "US"},
    {"id": "uso", "type": "asset", "label": "Oil ETF", "symbol": "USO", "market": "US"},
    {"id": "xlf", "type": "asset", "label": "Financials ETF", "symbol": "XLF", "market": "US"},
    {"id": "ita", "type": "asset", "label": "Defense ETF", "symbol": "ITA", "market": "US"},
    {"id": "tlt", "type": "asset", "label": "20Y+ Treasury ETF", "symbol": "TLT", "market": "US",
     "aliases": ["long bonds"]},
    {"id": "vgk", "type": "asset", "label": "Europe ETF", "symbol": "VGK", "market": "US"},
    {"id": "ewj", "type": "asset", "label": "Japan ETF", "symbol": "EWJ", "market": "US"},
    {"id": "inda", "type": "asset", "label": "India ETF", "symbol": "INDA", "market": "US"},
    {"id": "dba", "type": "asset", "label": "Agriculture ETF", "symbol": "DBA", "market": "US"},
    # ------------- assets: HK / China -------------
    {"id": "tencent", "type": "asset", "label": "Tencent", "symbol": "0700.HK", "market": "HK",
     "aliases": ["700.HK", "wechat"]},
    {"id": "baba", "type": "asset", "label": "Alibaba", "symbol": "9988.HK", "market": "HK",
     "aliases": ["alibaba", "taobao"]},
    {"id": "meituan", "type": "asset", "label": "Meituan", "symbol": "3690.HK", "market": "HK"},
    {"id": "byd", "type": "asset", "label": "BYD", "symbol": "1211.HK", "market": "HK"},
    {"id": "icbc", "type": "asset", "label": "ICBC", "symbol": "1398.HK", "market": "HK",
     "aliases": ["601398.SS", "industrial and commercial bank"]},
    {"id": "moutai", "type": "asset", "label": "Kweichow Moutai", "symbol": "600519.SS",
     "market": "CN", "aliases": ["moutai", "kweichow"]},
    {"id": "catl", "type": "asset", "label": "CATL", "symbol": "300750.SZ", "market": "CN",
     "aliases": ["contemporary amperex"]},
    {"id": "trackerfund", "type": "asset", "label": "Tracker Fund (HSI)", "symbol": "2800.HK",
     "market": "HK", "aliases": ["hang seng index", "hsi"]},
    # ------------- assets: Singapore -------------
    {"id": "dbs", "type": "asset", "label": "DBS", "symbol": "D05.SI", "market": "SG",
     "aliases": ["D05.SG", "dbs bank"]},
    {"id": "ocbc", "type": "asset", "label": "OCBC", "symbol": "O39.SI", "market": "SG",
     "aliases": ["O39.SG"]},
    {"id": "uob", "type": "asset", "label": "UOB", "symbol": "U11.SI", "market": "SG",
     "aliases": ["U11.SG", "united overseas bank"]},
    {"id": "sti_etf", "type": "asset", "label": "STI ETF", "symbol": "ES3.SI", "market": "SG",
     "aliases": ["straits times index"]},
    {"id": "cict", "type": "asset", "label": "CapitaLand Integrated Commercial Trust",
     "symbol": "C38U.SI", "market": "SG", "aliases": ["capitaland", "cict"]},
    # ------------- assets: crypto -------------
    {"id": "btc", "type": "asset", "label": "Bitcoin", "symbol": "BTC/USD", "market": "CRYPTO",
     "aliases": ["btc"]},
    {"id": "eth", "type": "asset", "label": "Ethereum", "symbol": "ETH/USD", "market": "CRYPTO",
     "aliases": ["eth", "ether"]},
    {"id": "sol", "type": "asset", "label": "Solana", "symbol": "SOL/USD", "market": "CRYPTO",
     "aliases": ["sol"]},
]

SEED_EDGES = [
    # ---- factor -> factor (the macro field itself) ----
    {"src": "us_inflation", "dst": "fed_rate", "type": "influences", "sign": 1, "weight": 0.8,
     "note": "hot inflation forces hikes / delays cuts"},
    {"src": "fed_rate", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "fed_rate", "dst": "usd_strength", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "fed_rate", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "fed_rate", "dst": "mas_policy", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "SG imports US rates via the SGD peg framework"},
    {"src": "us_10y_yield", "dst": "us_megacap_tech", "type": "influences", "sign": -1,
     "weight": 0.6, "note": "duration: long-dated cashflows discount harder"},
    {"src": "us_10y_yield", "dst": "sg_reits", "type": "influences", "sign": -1, "weight": 0.7,
     "note": "REIT financing costs + yield competition"},
    {"src": "us_10y_yield", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "real yields are gold's opportunity cost"},
    {"src": "usd_strength", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "usd_strength", "dst": "copper_price", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "usd_strength", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "usd_strength", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "strong USD = EM outflows"},
    {"src": "risk_appetite", "dst": "crypto_liquidity", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "risk_appetite", "dst": "us_megacap_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "risk_appetite", "dst": "gold_price", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "risk_appetite", "dst": "consumer_staples", "type": "influences", "sign": -1,
     "weight": 0.4, "note": "defensives outperform when risk appetite falls"},
    {"src": "global_growth", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "global_growth", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "global_growth", "dst": "risk_appetite", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "oil_price", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.6,
     "delay_days": 30, "note": "pump prices feed CPI with ~a month lag"},
    {"src": "oil_price", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "geopolitical_tension", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "geopolitical_tension", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "geopolitical_tension", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "yen_carry", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "BOJ tightening (node up) unwinds carry -> global risk-off"},
    {"src": "opec", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.7,
     "note": "supply cuts (actor acting) lift price"},
    # ---- world-systems additions: liquidity, credit, real economy, τ-lags ----
    {"src": "fed_rate", "dst": "money_supply", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "hikes + QT drain liquidity"},
    {"src": "fed_rate", "dst": "global_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "delay_days": 120, "note": "monetary policy hits the real economy with long lags"},
    {"src": "fed_rate", "dst": "credit_conditions", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "money_supply", "dst": "risk_appetite", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "money_supply", "dst": "crypto_liquidity", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "money_supply", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "money_supply", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.4,
     "delay_days": 180, "note": "monetary inflation is the slowest cascade in the field"},
    {"src": "us_gov_debt", "dst": "us_10y_yield", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "issuance supply pressures the long end"},
    {"src": "us_gov_debt", "dst": "gold_price", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "credit_conditions", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.6,
     "delay_days": 60, "note": "a crunch chokes activity ~a quarter later"},
    {"src": "credit_conditions", "dst": "us_financials", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "bank stress = credit down = financials down"},
    {"src": "us_employment", "dst": "us_consumer", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "us_employment", "dst": "fed_rate", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "hot labor keeps policy hawkish"},
    {"src": "us_consumer", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_elections", "dst": "us_china_tariffs", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "campaign seasons escalate trade rhetoric"},
    {"src": "us_elections", "dst": "risk_appetite", "type": "influences", "sign": -1, "weight": 0.2},
    {"src": "sanctions", "dst": "geopolitical_tension", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "sanctions", "dst": "oil_price", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "energy sanctions constrain supply"},
    {"src": "shipping_costs", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.5,
     "delay_days": 45},
    {"src": "shipping_costs", "dst": "global_growth", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "geopolitical_tension", "dst": "shipping_costs", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "chokepoint risk (Red Sea, Hormuz) reroutes trade"},
    {"src": "us_china_tariffs", "dst": "rare_earths", "type": "influences", "sign": 1, "weight": 0.4,
     "note": "escalation triggers China's export-curb counter-lever"},
    {"src": "china_government", "dst": "rare_earths", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "rare_earths", "dst": "semis", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "rare_earths", "dst": "ev_supply_chain", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "rare_earths", "dst": "defense_industry", "type": "influences", "sign": -1, "weight": 0.3},
    {"src": "natural_gas", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.3,
     "delay_days": 30},
    {"src": "natural_gas", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "ai_capex_cycle", "dst": "power_demand", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "power_demand", "dst": "natural_gas", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "power_demand", "dst": "energy_sector", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "geopolitical_tension", "dst": "defense_spending", "type": "influences", "sign": 1,
     "weight": 0.6, "delay_days": 90, "note": "budget cycles ratchet slowly"},
    {"src": "defense_spending", "dst": "defense_industry", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "us_10y_yield", "dst": "us_financials", "type": "influences", "sign": 1, "weight": 0.3,
     "note": "steeper curve helps NIMs (to a point)"},
    # ---- global coverage wiring (seed v3) ----
    {"src": "ecb_policy", "dst": "europe_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "delay_days": 90},
    {"src": "ecb_policy", "dst": "usd_strength", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "ECB hikes strengthen EUR = weaker DXY"},
    {"src": "europe_growth", "dst": "europe_equities", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "europe_growth", "dst": "global_growth", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "natural_gas", "dst": "europe_growth", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "energy-price shocks hit Europe hardest"},
    {"src": "yen_carry", "dst": "japan_equities", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "BOJ tightening = stronger yen = exporters down"},
    {"src": "global_growth", "dst": "japan_equities", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "global_growth", "dst": "india_growth", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "oil_price", "dst": "india_growth", "type": "influences", "sign": -1, "weight": 0.3,
     "note": "India is a large net oil importer"},
    {"src": "india_growth", "dst": "india_equities", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "usd_strength", "dst": "em_flows", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "em_flows", "dst": "india_equities", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "em_flows", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.3},
    {"src": "em_flows", "dst": "sg_banks", "type": "influences", "sign": 1, "weight": 0.2},
    {"src": "us_government", "dst": "us_tech_regulation", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_tech_regulation", "dst": "us_megacap_tech", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "us_government", "dst": "crypto_regulation", "type": "influences", "sign": 1, "weight": 0.4},
    {"src": "crypto_regulation", "dst": "crypto_liquidity", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "tightening chokes flows; approvals (node down) unlock them"},
    {"src": "oil_supply", "dst": "oil_price", "type": "influences", "sign": -1, "weight": 0.7},
    {"src": "opec", "dst": "oil_supply", "type": "influences", "sign": -1, "weight": 0.6,
     "note": "OPEC 'acting' = cutting quotas = fewer barrels"},
    {"src": "sanctions", "dst": "oil_supply", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "agri_food", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.3,
     "delay_days": 60},
    {"src": "agri_food", "dst": "china_consumer", "type": "influences", "sign": -1, "weight": 0.2},
    {"src": "vgk", "dst": "europe_equities", "type": "member_of", "weight": 0.9},
    {"src": "ewj", "dst": "japan_equities", "type": "member_of", "weight": 0.9},
    {"src": "inda", "dst": "india_equities", "type": "member_of", "weight": 0.9},
    {"src": "dba", "dst": "agri_food", "type": "correlates_with", "sign": 1, "weight": 0.8},
    # ---- US<->China policy ----
    {"src": "us_china_tariffs", "dst": "geopolitical_tension", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "us_china_tariffs", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.5},
    {"src": "us_china_tariffs", "dst": "ev_supply_chain", "type": "influences", "sign": -1,
     "weight": 0.6, "note": "CATL/BYD overseas expansion risk"},
    {"src": "us_china_tariffs", "dst": "us_inflation", "type": "influences", "sign": 1, "weight": 0.4,
     "delay_days": 45, "note": "tariffs reach shelf prices over ~6 weeks"},
    {"src": "china_export_controls", "dst": "semis", "type": "influences", "sign": -1, "weight": 0.7,
     "note": "China revenue haircut for NVDA et al"},
    {"src": "china_export_controls", "dst": "china_tech", "type": "influences", "sign": -1, "weight": 0.4},
    {"src": "us_government", "dst": "us_china_tariffs", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "us_government", "dst": "china_export_controls", "type": "influences", "sign": 1, "weight": 0.8},
    # ---- China cluster ----
    {"src": "pboc_rate", "dst": "china_financials", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "rate CUTS (node down) compress bank NIMs -> banks down"},
    {"src": "pboc_rate", "dst": "china_property", "type": "influences", "sign": -1, "weight": 0.5,
     "note": "cuts support property"},
    {"src": "china_government", "dst": "china_stimulus", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "china_government", "dst": "china_anti_corruption", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_stimulus", "dst": "china_consumer", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_stimulus", "dst": "china_property", "type": "influences", "sign": 1, "weight": 0.6},
    {"src": "china_stimulus", "dst": "copper_price", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_stimulus", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_property", "dst": "china_financials", "type": "influences", "sign": 1, "weight": 0.6,
     "note": "property NPLs sit on bank balance sheets"},
    {"src": "china_property", "dst": "china_consumer", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "wealth effect"},
    {"src": "china_consumer", "dst": "china_staples", "type": "influences", "sign": 1, "weight": 0.7},
    {"src": "china_consumer", "dst": "china_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "china_anti_corruption", "dst": "china_staples", "type": "influences", "sign": -1,
     "weight": 0.7, "note": "gifting/banquet demand collapses in campaigns (Moutai)"},
    {"src": "lithium_price", "dst": "ev_supply_chain", "type": "influences", "sign": -1, "weight": 0.4,
     "note": "cheap lithium helps battery/EV margins"},
    {"src": "ai_capex_cycle", "dst": "semis", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "ai_capex_cycle", "dst": "ai_datacenter", "type": "influences", "sign": 1, "weight": 0.8},
    {"src": "ai_capex_cycle", "dst": "us_megacap_tech", "type": "influences", "sign": 1, "weight": 0.5},
    {"src": "mas_policy", "dst": "sg_banks", "type": "influences", "sign": 1, "weight": 0.5,
     "note": "higher SG rates -> NIM tailwind"},
    {"src": "mas_policy", "dst": "sg_reits", "type": "influences", "sign": -1, "weight": 0.6},
    {"src": "crypto_liquidity", "dst": "crypto_majors", "type": "influences", "sign": 1, "weight": 0.8},
    # ---- membership (asset -> theme; shocks flow theme -> members) ----
    {"src": "aapl", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.8},
    {"src": "msft", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.8},
    {"src": "msft", "dst": "ai_datacenter", "type": "member_of", "weight": 0.6},
    {"src": "nvda", "dst": "semis", "type": "member_of", "weight": 0.9},
    {"src": "nvda", "dst": "ai_datacenter", "type": "member_of", "weight": 0.9},
    {"src": "tsla", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.8},
    {"src": "xlk", "dst": "us_megacap_tech", "type": "member_of", "weight": 0.9},
    {"src": "xle", "dst": "energy_sector", "type": "member_of", "weight": 0.9},
    {"src": "xlp", "dst": "consumer_staples", "type": "member_of", "weight": 0.9},
    {"src": "tencent", "dst": "china_tech", "type": "member_of", "weight": 0.9},
    {"src": "baba", "dst": "china_tech", "type": "member_of", "weight": 0.9},
    {"src": "meituan", "dst": "china_tech", "type": "member_of", "weight": 0.8},
    {"src": "byd", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.8},
    {"src": "byd", "dst": "china_tech", "type": "member_of", "weight": 0.4},
    {"src": "icbc", "dst": "china_financials", "type": "member_of", "weight": 0.9},
    {"src": "moutai", "dst": "china_staples", "type": "member_of", "weight": 0.9},
    {"src": "catl", "dst": "ev_supply_chain", "type": "member_of", "weight": 0.9},
    {"src": "trackerfund", "dst": "china_tech", "type": "member_of", "weight": 0.5},
    {"src": "trackerfund", "dst": "china_financials", "type": "member_of", "weight": 0.5},
    {"src": "dbs", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "ocbc", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "uob", "dst": "sg_banks", "type": "member_of", "weight": 0.9},
    {"src": "sti_etf", "dst": "sg_banks", "type": "member_of", "weight": 0.6,
     "note": "STI is ~half bank weight"},
    {"src": "cict", "dst": "sg_reits", "type": "member_of", "weight": 0.9},
    {"src": "btc", "dst": "crypto_majors", "type": "member_of", "weight": 0.9},
    {"src": "eth", "dst": "crypto_majors", "type": "member_of", "weight": 0.9},
    {"src": "sol", "dst": "crypto_majors", "type": "member_of", "weight": 0.8},
    # ---- supply / competition / proxies ----
    {"src": "catl", "dst": "tsla", "type": "supplies", "weight": 0.5,
     "note": "battery supplier relationship"},
    {"src": "byd", "dst": "tsla", "type": "competes_with", "weight": 0.4},
    {"src": "gld", "dst": "gold_price", "type": "correlates_with", "sign": 1, "weight": 0.9},
    {"src": "uso", "dst": "oil_price", "type": "correlates_with", "sign": 1, "weight": 0.9},
    {"src": "xlf", "dst": "us_financials", "type": "member_of", "weight": 0.9},
    {"src": "ita", "dst": "defense_industry", "type": "member_of", "weight": 0.9},
    {"src": "tlt", "dst": "us_10y_yield", "type": "correlates_with", "sign": -1, "weight": 0.9,
     "note": "yields up = long-bond prices down"},
]
